// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB59T2npWzxxb-L2ll23g8NOT9tsmfvtNk',
    appId: '1:156427984184:web:891758687b51015e5a75cd',
    messagingSenderId: '156427984184',
    projectId: 'transactai-881b6',
    authDomain: 'transactai-881b6.firebaseapp.com',
    storageBucket: 'transactai-881b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR8LmhnbozKvJulUSz_OAnTeLXW9Jt6MM',
    appId: '1:156427984184:android:d0b9fc0054e3b8815a75cd',
    messagingSenderId: '156427984184',
    projectId: 'transactai-881b6',
    storageBucket: 'transactai-881b6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB59T2npWzxxb-L2ll23g8NOT9tsmfvtNk',
    appId: '1:156427984184:web:2ce2ca52d3e2fcb55a75cd',
    messagingSenderId: '156427984184',
    projectId: 'transactai-881b6',
    authDomain: 'transactai-881b6.firebaseapp.com',
    storageBucket: 'transactai-881b6.firebasestorage.app',
  );
}
